from typing import Self, Protocol, TypeVar


class HasId(Protocol):
    id: int


DomainEnt = TypeVar("DomainEnt", bound=HasId)


class UoWInterface(Protocol):
    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, exc_type, exc_val, exc_tb) -> bool: ...
    def save(self, *ents: DomainEnt) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
